market/config/routes.rb
Rails.application.routes.draw do
  resources :joong_gos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

market/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

market/app/models/joong_go.rb
class JoongGo < ApplicationRecord
end

market/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

market/app/controllers/joong_gos_controller.rb
class JoongGosController < ApplicationController
  before_action :set_joong_go, only: [:show, :edit, :update, :destroy]

  # GET /joong_gos
  # GET /joong_gos.json
  def index
    @joong_gos = JoongGo.all
  end

  # GET /joong_gos/1
  # GET /joong_gos/1.json
  def show
  end

  # GET /joong_gos/new
  def new
    @joong_go = JoongGo.new
  end

  # GET /joong_gos/1/edit
  def edit
  end

  # POST /joong_gos
  # POST /joong_gos.json
  def create
    @joong_go = JoongGo.new(joong_go_params)

    respond_to do |format|
      if @joong_go.save
        format.html { redirect_to @joong_go, notice: 'Joong go was successfully created.' }
        format.json { render :show, status: :created, location: @joong_go }
      else
        format.html { render :new }
        format.json { render json: @joong_go.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joong_gos/1
  # PATCH/PUT /joong_gos/1.json
  def update
    respond_to do |format|
      if @joong_go.update(joong_go_params)
        format.html { redirect_to @joong_go, notice: 'Joong go was successfully updated.' }
        format.json { render :show, status: :ok, location: @joong_go }
      else
        format.html { render :edit }
        format.json { render json: @joong_go.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joong_gos/1
  # DELETE /joong_gos/1.json
  def destroy
    @joong_go.destroy
    respond_to do |format|
      format.html { redirect_to joong_gos_url, notice: 'Joong go was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joong_go
      @joong_go = JoongGo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joong_go_params
      params.require(:joong_go).permit(:팔기, :물건, :가격, :상태)
    end
end

market/app/helpers/application_helper.rb
module ApplicationHelper
end

market/app/helpers/joong_gos_helper.rb
module JoongGosHelper
end

market/app/views/joong_gos/_form.html.erb
<%= form_for(joong_go) do |f| %>
  <% if joong_go.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joong_go.errors.count, "error") %> prohibited this joong_go from being saved:</h2>

      <ul>
      <% joong_go.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :팔기 %>
    <%= f.text_field :팔기 %>
  </div>

  <div class="field">
    <%= f.label :물건 %>
    <%= f.text_area :물건 %>
  </div>

  <div class="field">
    <%= f.label :가격 %>
    <%= f.number_field :가격 %>
  </div>

  <div class="field">
    <%= f.label :상태 %>
    <%= f.check_box :상태 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

market/app/views/joong_gos/edit.html.erb
<h1>Editing Joong Go</h1>

<%= render 'form', joong_go: @joong_go %>

<%= link_to 'Show', @joong_go %> |
<%= link_to 'Back', joong_gos_path %>

market/app/views/joong_gos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joong Gos</h1>

<table>
  <thead>
    <tr>
      <th>팔기</th>
      <th>물건</th>
      <th>가격</th>
      <th>상태</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joong_gos.each do |joong_go| %>
      <tr>
        <td><%= joong_go.팔기 %></td>
        <td><%= joong_go.물건 %></td>
        <td><%= joong_go.가격 %></td>
        <td><%= joong_go.상태 %></td>
        <td><%= link_to 'Show', joong_go %></td>
        <td><%= link_to 'Edit', edit_joong_go_path(joong_go) %></td>
        <td><%= link_to 'Destroy', joong_go, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Joong Go', new_joong_go_path %>

market/app/views/joong_gos/new.html.erb
<h1>New Joong Go</h1>

<%= render 'form', joong_go: @joong_go %>

<%= link_to 'Back', joong_gos_path %>

market/app/views/joong_gos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>팔기:</strong>
  <%= @joong_go.팔기 %>
</p>

<p>
  <strong>물건:</strong>
  <%= @joong_go.물건 %>
</p>

<p>
  <strong>가격:</strong>
  <%= @joong_go.가격 %>
</p>

<p>
  <strong>상태:</strong>
  <%= @joong_go.상태 %>
</p>

<%= link_to 'Edit', edit_joong_go_path(@joong_go) %> |
<%= link_to 'Back', joong_gos_path %>

market/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>